language: go
sudo: false

os:
  - linux

# - osx

go:
  - 1.4.2
  - 1.5.3

# - tip

install:
 - go get ./...
 - '[[ `go version` =~ go1.[0-4][^0-9] ]] || go get -u github.com/kisielk/errcheck'
 - go get -u golang.org/x/tools/cmd/goimports
 - go get -u github.com/golang/lint/golint

script:
  - make check
  - go test -t -v ./...
  - go test -cpu=2 -race -v ./...
