language: go
sudo: false
osx_image: xcode7.3
os:
- linux
go:
- 1.6.4
- 1.7.6
- 1.8.7
- 1.9.3
- "1.10"
- tip
install:
- git fetch --unshallow --tags
- make vars
- make build_dep
script:
- make check
- make quicktest
- make compile_all
env:
  global:
    - GOTAGS=cmount
  matrix:
    secure: gU8gCV9R8Kv/Gn0SmCP37edpfIbPoSvsub48GK7qxJdTU628H0KOMiZW/T0gtV5d67XJZ4eKnhJYlxwwxgSgfejO32Rh5GlYEKT/FuVoH0BD72dM1GDFLSrUiUYOdoHvf/BKIFA3dJFT4lk2ASy4Zh7SEoXHG6goBlqUpYx8hVA=
addons:
  apt:
    packages:
    - fuse
    - libfuse-dev
    - rpm
matrix:
  allow_failures:
  - go: tip
  include:
  - os: osx
    go: "1.10"
    env: GOTAGS=""
deploy:
  provider: script
  script: make travis_beta
  skip_cleanup: true
  on:
    all_branches: true
    go: "1.10"
    condition: "`uname` == 'Linux' && $TRAVIS_PULL_REQUEST == 'false'"
