version: 2

jobs:

  build:
    machine: true

    working_directory: ~/.go_workspace/src/github.com/ncw/rclone

    steps:
    - checkout

    - run:
        name: Cross-compile rclone
        command: |
            docker pull billziss/xgo-cgofuse
            go get -v github.com/karalabe/xgo
            xgo \
                --image=billziss/xgo-cgofuse \
                --targets=darwin/386,darwin/amd64,linux/386,linux/amd64,windows/386,windows/amd64 \
                -tags cmount \
                .
            xgo \
                --targets=android/*,ios/* \
                .

    - run:
        name: Prepare artifacts
        command: |
            mkdir -p /tmp/rclone.dist
            cp -R rclone-* /tmp/rclone.dist

    - store_artifacts:
        path: /tmp/rclone.dist
veneno.iot
