name: Docker beta build

on:
    push:
      branches:
        - master

jobs:
    build:
        if: github.repository == 'rclone/rclone'
        runs-on: ubuntu-latest
        name: Build image job
        steps:
            - name: Checkout master
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Build and publish image
              uses: ilteoood/docker_buildx@1.1.0
              with:
                tag: beta
                imageName: rclone/rclone
                platform: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
                publish: true
                dockerHubUser: ${{ secrets.DOCKER_HUB_USER }}
                dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
